### ISSUE TITLE
Stuck with fmp4 output from ffmpeg I want to encrypt

### ISSUE THREAD

**Issue by venomone** [axiomatic-systems/Bento4#717] opened 2022-06-15 09:38 UTC
Hey folks,

as FFmpeg in version 5.0.1 (Currently latest) does not support fmp4 HLS encryption, process will end with "Encrypted fmp4 not yet supported", I would like to know If I could use bento4 as a workaround to encrypt my fmp4 hls segments here?

Currently, my setup takes a single mp4 input file, analysis this using ffprobe and generates multiple bit rate versions in HLS fmp4 format. So far so good, but how can I now protect these segments using encryption. As far as I've understood Bento4 SDK it expected to repack the file itself into HLS format from a single mp4. Is that true, or can I use Bento4 to reencrypt my segments here myself?

Thanks in advance

**Comment by barbibulle** [comment] 2022-07-17 16:30
Looks like this issue is a duplicate of #724

**Closed by barbibulle** 2022-07-17 16:30 UTC
