### ISSUE TITLE
iPhone HEVC CBCS playback issue

### ISSUE THREAD

**Issue by nilsandgren** [axiomatic-systems/Bento4#465] opened 2020-01-07 15:35 UTC
I'm having some problem playing back CBCS-encrypted HEVC on Apple devices.

The single-segment HEVC asset (uenc.cmfv in the provided ZIP file) is encrypted like so:

    #!/bin/bash
    
    KID=00112233445566778899aabbccddeeff
    KEY=fee1dff2b7165c53956cfd98f93711cd
    IV=000102030405060708090a0b0c0d0e0f
    
    ./mp4-dash.py -v -d --hls \
        --encryption-key=${KID}:${KEY}:${IV} \
        --encryption-cenc-scheme=cbcs \
        -o enc_hevc \
        uenc.cmfv

The KID, KEY, and IV seem to be accepted correctly since I see the following in the console output:

    Key Info for audio/video: KID=00112233445566778899aabbccddeeff, KEY=fee1dff2b7165c53956cfd98f93711cd, IV=000102030405060708090a0b0c0d0e0f

I put the key in key.bin and play master.m3u8 from my iPhone. Access log:

    192.168.103.18 - - [07/Jan/2020:15:59:28 CET] "GET /master.m3u8 HTTP/1.1" 200 445
    http://192.168.98.126:8765/ -> /master.m3u8
    192.168.103.18 - - [07/Jan/2020:15:59:28 CET] "GET /video/hev1/media.m3u8 HTTP/1.1" 200 344
    http://192.168.98.126:8765/ -> /video/hev1/media.m3u8
    192.168.103.18 - - [07/Jan/2020:15:59:29 CET] "GET /video/hev1/init.mp4 HTTP/1.1" 200 860
    http://192.168.98.126:8765/ -> /video/hev1/init.mp4
    192.168.103.18 - - [07/Jan/2020:15:59:29 CET] "GET /video/hev1/key.bin HTTP/1.1" 200 16
    http://192.168.98.126:8765/ -> /video/hev1/key.bin
    192.168.103.18 - - [07/Jan/2020:15:59:29 CET] "GET /video/hev1/seg-1.m4s HTTP/1.1" 200 2114710
    http://192.168.98.126:8765/ -> /video/hev1/seg-1.m4s

The screen remains gray and the video does not play.

I made a network capture of the communication, and even though the Ruby web
server claims that all 2114710 bytes of seg-1.m4s are streamed, the client
actually closes the connection after 860 KB (sending FIN, ACK). I suspect the
iOS player either crashes or atleast makes a hard exit.

I have included the network capture as ios.pcap in the provided ZIP file.

[hevc_cbcs.zip](https://github.com/axiomatic-systems/Bento4/files/4031290/hevc_cbcs.zip)

Creating unencrypted HLS output from the provided source file works fine!

**Comment by barbibulle** [comment] 2020-01-07 19:55
I'm able to reproduce the issue. I'll investigate and let you know.

**Comment by jimmymic** [comment] 2020-04-15 04:49
@barbibulle Did you uncover anything with this. 
I am wondering if I have a similar issue with CBCS causing a crash in Safari when playing HDR streams.
Will investigate further and try and get some details together but would be interested to know if you have found anything with this issue?

**Comment by barbibulle** [comment] 2020-04-17 19:17
I haven't found the time to investigate this yet. I'll try to look at it in the coming week.

**Comment by barbibulle** [comment] 2020-05-04 19:14
Ok, I finally found some time to look into this. It wasn't so obvious to find out what was going on, since there are no logs from the iPhone when the failure happens. Also, the fact that the same video plays when not encrypted confused the issue.
What's going on here is that the Apple player (at least on iPhones and recent versions of macOS) behaves differently for cleartext and encrypted content (which makes sense, since usually a DRM-capable playback subsystem will use its codec in a stricter mode, if not use a different codec implementation altogether in some cases). For encrypted content, only HEVC in 'hvc1' mode is supported (or, when using 'hev1', if all the parameter sets are signaled in the sample description *AND* the `array_completeness` field is set to 1).
If you tell your encoder/muxer to produce an 'hvc1', or convert your file from `hev1` mode to `hcv1` mode (which can be done without re-encoding). For example, using `ffmpeg`, this will do the conversion:
`ffmpeg -i input.mp4 -vcodec copy -acodec copy -tag:v hvc1 output.mp4`

**Comment by nilsandgren** [comment] 2020-05-12 06:58
Thanks for taking the time to make such a thorough investigation! I was suspecting that the parameter sets were somehow related to the issue, but could not get my head around it completely.

Sorry for wasting your time with this, but hopefully we both learned a thing or two about how things work in the world. You can close this if you want to, since as I see it, there is nothing wrong in how Bento4 handles the content.

**Comment by barbibulle** [comment] 2020-05-13 02:10
Sounds good. Closing. I'll try to write a warning note about this fact on the doc site.

**Closed by barbibulle** 2020-05-13 02:10 UTC
