### ISSUE TITLE
Bento4 apps and handler type

### ISSUE THREAD

**Issue by grylem** [axiomatic-systems/Bento4#317] opened 2018-09-06 06:54 UTC
After any action mp4dump/mp4edit etc. Bento4 apps removes handlers types "mhlr" and "dhlr" from hdlr atoms.
for example:
in hdlr atom
orig.mp4
type mhlr
subtype vide
name video
processed.mp4 - after mp4compact or any action with mp4edit
type
subtype vide
name video

Also mp4dump don't show info about mhlr or dhlr
mp4dump test.mp4
[hdlr] size=12+46
        handler_type = vide
        handler_name = Apple Video Media Handler
but test.mp4 contains mhlr and dhlr in hdlr atom.

**Comment by barbibulle** [comment] 2018-09-06 16:48
Would you be able to share an mp4 file with mhlr and dhlr handlers?

**Comment by grylem** [comment] 2018-09-06 19:13
of course
[hdlr.zip](https://github.com/axiomatic-systems/Bento4/files/2358430/hdlr.zip)

**Comment by grylem** [comment] 2018-09-09 07:09
Thanks!
Now after processing mp4 has mhlr and dhlr, but hdlr themselves have a difference(please see pictures)
this small offset was before you even added the support for mhlr/dhlr.  This is because of the difference in formats?
[screen.zip](https://github.com/axiomatic-systems/Bento4/files/2364037/screen.zip)

**Comment by barbibulle** [comment] 2018-09-10 00:28
That's caused by another quicktime legacy format difference with MP4: the handler name string in MP4 files is a NULL-terminated string, whereas with QuickTime, that's a length-prefixed string. I've pushed an update of the code that will try and write the handler name out in length-prefixed mode when that was the mode seen when initially read. Let me know if this works for you.

**Comment by grylem** [comment] 2018-09-10 06:31
many thanks, now perfect.
only mp4dump dont show presence mhlr/dhlr but this is not so important.

**Comment by barbibulle** [comment] 2018-09-23 18:39
The WARNING shouldn't be there. This indicates that the serializer isn't working exactly right. If you can send me a file and the exact command line you used that can replicate this problem, I should be able to fix it (I haven't seen it in my tests).

**Comment by grylem** [comment] 2018-09-24 06:34
**barbibulle**
for test you superior tools I prefer to use Apple's  m4v, m4a, m4b(I'm very sorry that Bento4 not completely compatible with QuickTime *.mov)
http://video.itunes.apple.com/apple-assets-us-std-000001/Video118/v4/66/c9/55/66c955ab-9044-266e-bf0d-7a8df5514bfc/mzvf_1582032123152368156.640x480.h264lc.U.p.m4v
mp4compact for this file
WARNING: atom serialized to fewer bytes than declared size
WARNING: atom serialized to fewer bytes than declared size
WARNING: atom serialized to fewer bytes than declared size

mp4edit --remove wide file out_file
WARNING: atom serialized to fewer bytes than declared size
WARNING: atom serialized to fewer bytes than declared size
WARNING: atom serialized to fewer bytes than declared size

**Comment by barbibulle** [comment] 2018-09-25 05:14
I pushed a fix to the master branch that should fix this.

**Comment by grylem** [comment] 2018-09-25 07:00
Thank you so much. I will test these changes with different files.
Now I found a *.mp4 that the mp4compact/mp4edit can not process but old versions can.
make this mp4
QuickTime Pro 7 ->export Movie to MPEG-4->options - pass through->qt_test.mp4
mp4compact qt_test.mp4 out.mp4
no any error but process does not end and out.mp4 size more and more
[qt_test.mp4.zip](https://github.com/axiomatic-systems/Bento4/files/2414097/qt_test.mp4.zip)
for mp4 made with Compressor 4 and avexport all fine.

**Comment by grylem** [comment] 2018-09-26 10:13
recent changes(better hdlr edge case handling) spoil mp4
one extra byte at the beginning mdat
0066F40E 6D646174 00009E2D 65888401 - working mp4
350066F4 0E6D6461 7400009E 2D658884 - processed and broken

**Comment by grylem** [comment] 2018-09-27 12:11
more info about this situation
mp4compact test.mp4 out.mp4
compile myself file has corrupted mdat
process file with your binary
Assertion failed: (bytes_written <= atom->GetSize()), function Action, file /Users/gilles/Workspace/Bento4/Source/C++/Core/Ap4Atom.cpp, line 759.
Abort trap: 6
and file does not have mdat
[test.mp4.zip](https://github.com/axiomatic-systems/Bento4/files/2423983/test.mp4.zip)

**Comment by barbibulle** [comment] 2018-12-02 08:54
This should be fixed now.

**Closed by barbibulle** 2018-12-02 08:54 UTC
Labels: enhancement
