### ISSUE TITLE
udta/​meta extraction/​insertion

### ISSUE THREAD

**Issue by alexbuisson** [axiomatic-systems/Bento4#30] opened 2015-10-08 08:27 UTC
Hi, I use Bento4 to extract atoms from mp4 and inject those atoms into new mp4 file and I found the following issue.
When I try to extract udta/meta atom with sub atom in the mdat atom (ie. hdlr, ilist, etc... see attached png file) Bento4 stop the parsing at the mdat level (why not ...) and claim as expected that the atom ise is for example 144 bytes. But when I do the 'moov->AddChild(udta->Clone());' in the output file there is an issue because the MP4 output file, the metaatom has only a size of 12 bytes and by the way all subboxes are not there !!!

![udta-mdat](https://cloud.githubusercontent.com/assets/1880818/10361174/99e3e9c0-6da6-11e5-9db6-1139d6050106.PNG)
.
Any help will be welcome !

here is the pseudo-code I used to extract the atom (note that in the real code all return are checked with 'AP4_FAILED' and no error is found .... )

    AP4_Atom extract(...) {
       AP4_ByteStream input = NULL;
       AP4_Result result = AP4_FileByteStream::Create(input_name.c_str(),  AP4_FileByteStream::STREAM_MODE_READ, input);
       if (AP4_FAILED(result)) {
          return NULL;
       }

      // parse the atoms
      AP4_AtomParent top_level;
      AP4_Atom atom;
      AP4_AtomFactory& atom_factory = AP4_DefaultAtomFactory::Instance;
       while (atom_factory.CreateAtomFromStream(input, atom) == AP4_SUCCESS) {
           top_level.AddChild(atom);
      }

     atom = top_level.FindChild("moov/udta");
     if (atom == NULL)
     {
           return NULL;
     }
     result = atom->Detach();
     input->Release();
     return atom;
    }

and the pseudo-code use to insert

    void insert(AP4_Atom atom)
    {
         AP4_Movie movie = new AP4_Movie(civox->media_timescale);
         AP4_File file(movie);
         ....
        AP4_MoovAtom moov = movie->GetMoovAtom();
        result = moov->AddChild(atom->Clone());
        ....
        AP4_ByteStream output;
        result = AP4_FileByteStream::Create (mp4File, AP4_FileByteStream::STREAM_MODE_WRITE, output);
        result = AP4_FileWriter::Write(file, *output);
        output->Release();
         ....
    }

**Comment by barbibulle** [comment] 2015-10-08 20:48
Hi Alex,

this should work in theory. I will take a look at your example and double
check. I'll let you know what I find out.

**Comment by barbibulle** [comment] 2015-10-09 05:29
Based on this sample code, it is normal that you end up with an empty 'mdat' atom in your output file: you are creating a new output movie object, to which you add a clone of your input 'udta' atom. So in the output you will find a 'moov' atom with the clone of your input 'udta', followed by an empty 'mdat'. The 'mdat' atom contains the media samples for your files, so if you don't add any samples to your output movie object, there won't be any in the output.

Maybe you can describe the scenario you are trying to implement, so I can guide you in the right direction?

**Comment by alexbuisson** [comment] 2015-10-09 07:02
Hi,
thank you for the reply, I edited my initial report because I made a mistake the atom I want to extract is a metadata `meta`atom (not the `mdat`...)

I tried to reproduce the issue with `mp4extract` and I get exactly the same behavior with a warning message:

    mp4extract moov/udta metadata.mp4 udta.bin
    WARNING: atom serialized to fewer bytes than declared size

    hexdump -C udta.bin
    00000000  00 00 00 98 75 64 74 61  00 00 00 90 6d 65 74 61  |....udta....meta|
    00000010  00 00 00 89 00 00 00 00  00 00 00 00 00 00 00 00  |................|
    00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

But as you could see in the attached PNG file the udta data are really different:

![udta](https://cloud.githubusercontent.com/assets/1880818/10387700/da5d72c4-6e63-11e5-833d-a673519e56d6.PNG)

**Comment by alexbuisson** [comment] 2015-10-09 07:31
More infos:
after a bit of debugging with gdb it looks like the issue come from the parser, because the `meta` doesn't have children and that's why the `AP4_ContainerAtom::WriteFields` return `AP4_SUCCESS` even if it doesn't write any thing (like if it was a leaf) 

If the parsing was correct we should have at least 2 childrens (see the 1st snapshot of the udta/meta tree), an `hdlr` atom and a `ilist`

**Comment by alexbuisson** [comment] 2015-10-09 14:14
00 00 00 98 75 64 74 61 (udta size 152) 00 00 00 90 6d 65 74 61 (meta size 144) 00 00 00 89 (that's the issue after 0x89 a type is expected but there is nothing) 00 00 00 21 68 64 6c 72 (hdlr atom size 33)

if I just fix/ignore the byte of value 0x89 the parsing is perfect and I'm able to get all the sub atom !

**Comment by barbibulle** [comment] 2015-10-09 16:10
Could you send me a file that exhibits this issue? (I'm not able to
reproduce this with my own files)

**Comment by alexbuisson** [comment] 2015-10-12 11:15
Hi, as I cannot share the video content, I removed all the mdat atom so the video is not playable ! But you should be able to reproduce the issue using the file I uploaded here https://drive.google.com/file/d/0BxpKFXPCGGNNN2dsNHl1T1hlb2s/view?usp=sharing

    mp4extract moov/udta ../test_meta.mp4 udta.bin
    WARNING: atom serialized to fewer bytes than declared size

**Comment by barbibulle** [comment] 2015-10-14 04:10
I found the issue here. For some reason, the tool that created your
original file has created a strange 'meta' box, with version=0x89 (only
version=0 has ever been defined in the ISO spec or the Quicktime spec, so
it is unclear why a tool would put a value of 0x89 there...).
In addition, the Bento4 parser has a special handling routine for 'meta'
box because some older versions of quicktime didn't always make this a
'full' box, so the parser has to be smart and try to detect that situation
automatically. Unfortunately, the code that does this autodetection had a
small bug, which would cause it to fail when a non-0 value is used for the
version field.
This is now fixed in the master branch on GitHub, so you can compile from
source. I will post updated binaries soon.

**Comment by alexbuisson** [comment] 2015-10-14 08:02
Hi, as I cannot share the video content, I removed all the mdat atom so the video is not playable ! But you should be able to reproduce the issue using the file I uploaded here https://drive.google.com/file/d/0BxpKFXPCGGNNN2dsNHl1T1hlb2s/view?usp=sharing

    mp4extract moov/udta ../test_meta.mp4 udta.bin
    WARNING: atom serialized to fewer bytes than declared size

**Comment by alexbuisson** [comment] 2015-10-14 08:04
Great and thank you for help....

PS: I like your nickname :) so if you see them, says hello for me to the other member of the 'barabapapa' family !!!!!

**Comment by barbibulle** [comment] 2015-11-06 18:02
This should be fixed now.

**Closed by barbibulle** 2015-11-06 18:02 UTC
