### ISSUE TITLE
AC3 support not fully implemented yet

### ISSUE THREAD

**Issue by mlevkov** [axiomatic-systems/Bento4#78] opened 2016-06-23 03:52 UTC
Hello,

I'm getting an error while trying to process an mp4 file with AC3 audio in it. Is that an expected behavior?
The error that I'm getting is AC3 support not fully implemented yet. 

Regards,
Max

**Comment by barbibulle** [comment] 2016-06-23 05:51
EAC-3 (aka Dolby Digital Plus) should be fully supported. "old" AC-3 (aka Dolby Digital) hasn't received as much testing. Can you share the file that you're having a problem with so that I can take a look?

**Comment by mlevkov** [comment] 2016-06-23 19:36
Thank you for your quick response. Here is the short 1min audio: 
https://www.dropbox.com/s/smadvbm6btt62bo/test_ac3_t60.mp4?dl=0

Looking forward to your response.

**Comment by barbibulle** [comment] 2016-06-23 20:00
Thanks. The issue is caused by a bug that was introduced recently that impacts audio-only files with mp4-dash.py. 
I have pushed a fix for mp4-dash.py to the master branch. If you want to try that without waiting for a new pre-compiled release, you can just replace this file in your distribution (only this python tool has changed, so no need to recompile the native executables)

**Comment by mlevkov** [comment] 2016-06-23 20:35
I've used this with hls packager. Could you please tell me if you are able to make this modification for hls python packager?

**Comment by barbibulle** [comment] 2016-06-23 21:28
I only looked at the DASH packager. I will look at the HLS packager and followup shortly

**Comment by barbibulle** [comment] 2016-06-23 22:14
I have tested your file with HLS and I'm not encountering any error:
mp4hls test_ac3_t60.mp4

This gives me a master playlist with:
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=423526,BANDWIDTH=424673,CODECS="ac-3"

and a media playlist with 5 segments.

What error are you getting on your side?

**Comment by mlevkov** [comment] 2016-06-24 00:07
Thank you for noting it. I will try it individually with mp4hls. When running mp4-hls.py, I get the following error:
ERROR: AC3 support not fully implemented yet
Traceback (most recent call last):
  File "/Downloads/Bento4-SDK-1-5-0-612.universal-apple-macosx/utils/mp4-hls_maxim_06142016.py", line 422, in <module>
    main()
  File "/Downloads/Bento4-SDK-1-5-0-612.universal-apple-macosx/utils/mp4-hls_maxim_06142016.py", line 412, in main
    OutputMuxedHls(options, media_sources)
  File "/Downloads/Bento4-SDK-1-5-0-612.universal-apple-macosx/utils/mp4-hls_maxim_06142016.py", line 115, in OutputMuxedHls
    json_info = Mp42Hls(options, media_source.filename, **kwargs)
  File "/Downloads/Bento4-SDK-1-5-0-612.universal-apple-macosx/utils/mp4utils.py", line 294, in Mp42Hls
    return Bento4Command(options, 'mp42hls', input_filename, *args, **kwargs)
  File "/Downloads/Bento4-SDK-1-5-0-612.universal-apple-macosx/utils/mp4utils.py", line 273, in Bento4Command
    raise Exception(message)
Exception: binary tool failed with error 1

Process finished with exit code 1

**Comment by mlevkov** [comment] 2016-06-24 01:11
I've tried to run the packager with HLS and it worked fine unencrypted, as you suggested. However, when I invoked the following encryption options:
--encryption-mode=SAMPLE-AES
--encryption-iv-mode=fps
--encryption-key={'''''' removed it for sensitivity '''''}
--encryption-key-uri={'''''' removed it for sensitivity '''''}
--encryption-key-format={'''''' removed it for sensitivity '''''}
--encryption-key-format-versions=1
I then received the error that I previously reported:
ERROR: AC3 support not fully implemented yet
ERROR: binary tool failed with error 1

**Comment by barbibulle** [comment] 2016-06-24 03:36
I see what you mean. Indeed, SAMPLE-AES encryption for AC-3 media isn't there yet (it needs some special descriptor). I'll try to add it in the next few days.

**Comment by mlevkov** [comment] 2016-06-24 17:28
Thank you! Very much appreciate that.

**Comment by mlevkov** [comment] 2016-06-28 22:19
I'm not sure the level of effort this requires. Just kindly curious to know if you were able to make any progress on this.

**Comment by barbibulle** [comment] 2016-06-28 23:07
It isn't a huge effort, but I haven't yet had time to finish it. Also, it is not clear how to test the feature. I don't know if you know of a way to force an iOS or OS X client to play the AC-3 or EAC-3 variant in a playlist, but all the clients I've tried behave like this:
* if the playlist only has AC-3 or EAC-3, the playlist is refused
* if the playlist has AAC in addition to AC-3 and/or EAC-3, the playlist plays but there's no UI to select the AC-3 or EAC-3 variant, so it isn't clear whether it is accepted.

I can play an AC-3 only HLS playlist with non-Apple clients (like ffplay for example), but I would want to verify that what's produced by Bento4 is accepted by Apple clients.

**Comment by mlevkov** [comment] 2016-06-29 01:29
Here is some reference detail that might guide you along:
https://developer.apple.com/library/tvos/documentation/General/Reference/HLSAuthoringSpec/Requirements.html

The way I've been able to test this is by using the Apple TV in development. What I've noticed is that you have to have AC3 and EAC3, as per spec, in the same m3u8 container, for compatibility and fallback. AAC is specified as default and mandatory for streams that contain AC3 and EAC3. What drives the selection is GROUP tag and consequential use of the AC3 and EAC3. I've been modifying mp4-hls.py to enable grouping functionality, which I woud be open to share with you, just let me know how to send it. It is not quite ready for public usage yet. 

The following link contains examples (see Apple TV) that would outline the targeted formatting and specification. https://developer.apple.com/streaming/examples/

I could help you test these. We have DRM Development Environment, we just need to be able to encrypt individual AC3 and EAC3, since AAC is already enabled, then I can combine these in the package and test on the actual device.   
Take a look at the attached file and note the presence of AAC, AC3, and EAC3. 
[atv_master.txt](https://github.com/axiomatic-systems/Bento4/files/338356/atv_master.txt)

**Comment by mlevkov** [comment] 2016-06-29 23:02
Is there is a version of the packager that I can try to run these tests with? I can help you with that part.

**Comment by barbibulle** [comment] 2016-06-30 05:24
Not yet, but I'm working on it this week.

**Comment by mlevkov** [comment] 2016-06-30 19:06
Awesome. Thank you! I have everything ready for test.

**Comment by mlevkov** [comment] 2016-07-05 18:37
Hello,

I hope all is well. Just want to ask if you were able to get to a point where I can help you test this feature yet?

Highest Regards,
Max

**Comment by barbibulle** [comment] 2016-07-06 01:43
Almost there. encrypted H.264, AAC and E-AC3 works great. Just need to finish AC3 (Apple added some bizarro mode for AC3, where part of an audio frame needs to be included in the audio setup data…) 

-- Gilles


On July 5, 2016 at 11:37:04 AM, mlevkov (notifications@github.com) wrote:

Hello,

I hope all is well. Just want to ask if you were able to get to a point where I can help you test this feature yet?

Highest Regards,
Max

**Comment by mlevkov** [comment] 2016-07-08 17:32
Sounds awesome. Please let me know when you have it ready, so that I can test it right away.

**Comment by barbibulle** [comment] 2016-07-14 19:01
I have committed an update that should work for you (also published pre-compiled binaries on the website). Let me know if you have any trouble with it.

**Comment by mlevkov** [comment] 2016-07-15 00:36
This is awesome. Let me test those and let you know how it works out. Thank you for your diligent effort. Very much appreciate that.

**Comment by mlevkov** [comment] 2016-07-23 00:14
Hello, we have tested group packaging and have experienced audio issues (not yet encrypted):
1. Audio Synchronization is experiencing problems.
- Source file contains no audio essences and only 3 separate audio files in mp4 container are presented for packaging (AAC, AC3, E-AC3). Observations: In the initial playback, audio and video is present and plays back in sync. After random seek, pause, and seek again using the handheld remote, the audio and video drifts from each other. 
2. No switch occurs to group audio on the Apple TV devices. 
When mp4 is given with audio/video mux and packaged by Bento4 in group where AAC, AC-3, and E-AC3 is present. The audio decoder does not get packaged group overrides. In other words, the audio from the "group" shows in the receiver as being switched, but never gets assigned the appropriate audio decoder. We tested this with silent audio essence and video in premuxed mp4 and proper audio in the grouped audio.

**Comment by barbibulle** [comment] 2016-07-26 00:38
I'll take a look at this.

**Comment by mlevkov** [comment] 2016-07-28 18:44
Let me know if you need me to do some additional testing or some other things to help you isolate this issue, or if you are even observing the case.

**Comment by barbibulle** [comment] 2016-07-28 18:58
I'm planning on looking at this tomorrow. If you can share some of the media files you've been using, as well as the command line arguments you have used. That may help me reproduce the issue (in case it has something to do with some of the specifics of the media you're using)

**Comment by mlevkov** [comment] 2016-08-11 22:29
Hello,
I'm happy to inform you that the fix for this issue has worked and passed the playback with Fairplay on AppleTV, while being able to decrypt and decode encrypted audio among the three audio streams. Thank you for your cooperation and great support.

**Comment by sannies** [comment] 2016-11-02 13:32
Thanks for your awesome work. When will this be available in a public build? Or is it something else when I still get the "AC3 support not fully implemented yet" error message?

**Comment by barbibulle** [comment] 2016-11-03 17:27
Hi Sebastian,

full support for AC3 should be checked in to the master branch. It is
possible that the binary release is one release behind, I will check and
fix that if this is the case. Have you tried the master branch?

**Comment by sannies** [comment] 2016-11-15 05:48
Hi Gilles, 
in deed it's in the master branch. I didn't even think that this might be the case as the latest activity on this ticket was quite old. I'll build it myself. 
Grüße,
Sebastian

**Closed** 2017-05-27 19:12 UTC
